### ISSUE TITLE
Integration setup fails after restart, error shows up in logs

### ISSUE THREAD

**Issue by sMauldaeschle** [hellqvio86/home_assistant_casambi#87]
**Describe the bug**

Since some version between v0.106 (confirmed working) and v0.110 the setup of the integration fails.

**To Reproduce**

Boot/restart hassio, integration will not setup and raise and error in the logs (see below).

**Expected behavior**

Clean setup without any errors.

**Debug logs**

Provide debug logs for integration and aiocasambi in plain text, remove credentials. Enable them through *configuration.yaml* e.g:

```
This error originated from a custom integration.

Logger: homeassistant.config_entries
Source: custom_components/casambi/utils.py:78
Integration: Casambi (documentation, issues)
First occurred: 11:06:59 AM (1 occurrences)
Last logged: 11:06:59 AM

Error setting up entry Casambi for casambi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/casambi/__init__.py", line 45, in async_setup_entry
    controller = hass.data[DOMAIN][CONF_CONTROLLER] = await async_create_controller(hass, config)
  File "/config/custom_components/casambi/utils.py", line 78, in async_create_controller
    await aiocasambi_controller.initialize()
  File "/usr/local/lib/python3.10/site-packages/aiocasambi/controller.py", line 602, in initialize
    await self.init_unit_state_controls(network_id=network_id)
  File "/usr/local/lib/python3.10/site-packages/aiocasambi/controller.py", line 411, in init_unit_state_controls
    network_id = match.group("network_id")
AttributeError: 'NoneType' object has no attribute 'group'
```

**Screenshots**

**Platform information (please complete the following information):**

 - OS: hassio on raspberry Pi, OS version: 9.3
 - Home assistant version: 2022.11.5

**Additional context**

**Comment by robsonke** [comment]
I had more or less the same issue. I switched from Yaml to the UI Integration and that solved it for me.

**Comment by hellqvio86** [comment]
Please provide debug logs

**Comment by hellqvio86** [comment]
It's great of you move away from configuration.yaml, that code path will soon be removed.

**Comment by sMauldaeschle** [comment]
I did copy some parts of the log file (because of the personal data). What I could see is that it exactly fails when it comes to unit_id 7 (see second part of the logs). In the first part of the logs you can see that the unique_ids are incomplete from that id on. It looks like the received units send an empty 'address'. The ones with empty 'address' values are all Hue lights.

```
2022-12-05 19:26:06.520 DEBUG (MainThread) [aiocasambi.units] process_network_state - data={'activeScenes': [],
 'address': '1714f5d1702b',
 'dimLevel': 0.21241830065359477,
 'gateway': {'name': 'S87'},
 'grade': 'CLASSIC',
 'groups': {'2': {'id': 2,
                  'name': 'Hue Living Room',
                  'position': 4,
                  'units': [{'id': 1001, 'position': 0},
                            {'id': 1002, 'position': 1},
                            {'id': 1003, 'position': 2}]},
            '3': {'id': 3,
                  'name': 'Hue Living Room Fi',
                  'position': 7,
                  'units': [{'id': 1008, 'position': 0},
                            {'id': 1009, 'position': 1},
                            {'id': 1010, 'position': 2}]}},
 'id': 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR',
 'name': 'DanielNetwork',
 'photos': [],
 'revision': 90,
 'scenes': {'1': {'color': '#FFFFFF',
                  'hidden': False,
                  'icon': 0,
                  'id': 1,
                  'name': 'Hell',
                  'position': 0,
                  'type': 'REGULAR',
                  'units': {'1': {'id': 1},
                            '1001': {'id': 1001},
                            '1002': {'id': 1002},
                            '1003': {'id': 1003},
                            '1004': {'id': 1004},
                            '1008': {'id': 1008},
                            '1009': {'id': 1009},
                            '1010': {'id': 1010},
                            '2': {'id': 2}}},
            '2': {'color': '#FFFFFF',
                  'hidden': False,
                  'icon': 0,
                  'id': 2,
                  'name': 'Halbhell',
                  'position': 1,
                  'type': 'REGULAR',
                  'units': {'1': {'id': 1},
                            '1001': {'id': 1001},
                            '1002': {'id': 1002},
                            '1003': {'id': 1003},
                            '1004': {'id': 1004},
                            '1008': {'id': 1008},
                            '1009': {'id': 1009},
                            '1010': {'id': 1010},
                            '2': {'id': 2}}},
            '3': {'color': '#FFFFFF',
                  'hidden': False,
                  'icon': 0,
                  'id': 3,
                  'name': 'Time to chill',
                  'position': 2,
                  'type': 'REGULAR',
                  'units': {'1': {'id': 1},
                            '1001': {'id': 1001},
                            '1002': {'id': 1002},
                            '1003': {'id': 1003},
                            '1004': {'id': 1004},
                            '1008': {'id': 1008},
                            '1009': {'id': 1009},
                            '1010': {'id': 1010},
                            '2': {'id': 2}}},
            '4': {'color': '#FFFFFF',
                  'hidden': False,
                  'icon': 0,
                  'id': 4,
                  'name': 'Nur Tisch',
                  'position': 3,
                  'type': 'REGULAR',
                  'units': {'1': {'id': 1},
                            '1001': {'id': 1001},
                            '1002': {'id': 1002},
                            '1003': {'id': 1003},
                            '1004': {'id': 1004},
                            '2': {'id': 2}}}},
 'timezone': 'Europe/Berlin',
 'type': 'PROTECTED',
 'units': {'1': {'activeSceneId': 0,
                 'address': 'be08f02ce486',
                 'condition': 0,
                 'controls': [[{'name': 'dimmer0',
                                'type': 'Dimmer',
                                'value': 0.32941176470588235},
                               {'name': 'vertical',
                                'type': 'Vertical',
                                'value': 1.0}]],
                 'dimLevel': 0.6647058823529411,
                 'firmwareVersion': '26.24',
                 'fixtureId': 816,
                 'groupId': 0,
                 'id': 1,
                 'name': 'Sento',
                 'on': False,
                 'online': False,
                 'position': 0,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'Luminaire'},
           '1001': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 2,
                    'id': 1001,
                    'name': 'Hue color lamp 1',
                    'on': False,
                    'online': False,
                    'position': 0,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1002': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 2,
                    'id': 1002,
                    'name': 'Hue color lamp 2',
                    'on': False,
                    'online': False,
                    'position': 1,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1003': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 2,
                    'id': 1003,
                    'name': 'Hue color lamp 3',
                    'on': False,
                    'online': False,
                    'position': 2,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1004': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 0,
                    'id': 1004,
                    'name': 'Hue Iris 1',
                    'on': False,
                    'online': False,
                    'position': 5,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1005': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[]],
                    'fixtureId': 100002,
                    'groupId': 0,
                    'id': 1005,
                    'name': 'Hue Aurelle Panel 1',
                    'on': False,
                    'online': False,
                    'position': 6,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1008': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[]],
                    'fixtureId': 100001,
                    'groupId': 3,
                    'id': 1008,
                    'name': 'Hue filament bulb 1',
                    'on': False,
                    'online': False,
                    'position': 0,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1009': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[]],
                    'fixtureId': 100001,
                    'groupId': 3,
                    'id': 1009,
                    'name': 'Hue filament bulb 2',
                    'on': False,
                    'online': False,
                    'position': 1,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1010': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[]],
                    'fixtureId': 100001,
                    'groupId': 3,
                    'id': 1010,
                    'name': 'Hue filament bulb 3',
                    'on': False,
                    'online': False,
                    'position': 2,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1011': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 0,
                    'id': 1011,
                    'name': 'Hue Play 1',
                    'on': False,
                    'online': False,
                    'position': 8,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1012': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 0,
                    'id': 1012,
                    'name': 'Hue Play 2',
                    'on': False,
                    'online': False,
                    'position': 9,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '1013': {'activeSceneId': 0,
                    'address': '',
                    'condition': 0,
                    'controls': [[{'name': 'dimmer0',
                                   'type': 'Dimmer',
                                   'value': 0.0}]],
                    'dimLevel': 0.0,
                    'fixtureId': 1,
                    'groupId': 0,
                    'id': 1013,
                    'name': 'Hue Play 3',
                    'on': False,
                    'online': False,
                    'position': 10,
                    'priority': 0,
                    'status': 'ok',
                    'type': 'Luminaire'},
           '2': {'activeSceneId': 0,
                 'address': 'eb3eb1c38a05',
                 'condition': 0,
                 'controls': [[{'name': 'dimmer0',
                                'type': 'Dimmer',
                                'value': 0.0},
                               {'name': 'vertical',
                                'type': 'Vertical',
                                'value': 1.0}]],
                 'dimLevel': 0.5,
                 'firmwareVersion': '26.24',
                 'fixtureId': 816,
                 'groupId': 0,
                 'id': 2,
                 'name': 'Sento verticale',
                 'on': False,
                 'online': False,
                 'position': 1,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'Luminaire'},
           '3': {'activeSceneId': 0,
                 'address': 'e2150000bc90',
                 'condition': 0,
                 'controls': [[]],
                 'fixtureId': 200001,
                 'groupId': 0,
                 'id': 3,
                 'name': 'PTM215B',
                 'on': False,
                 'online': False,
                 'position': 6,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'BatterySwitch'},
           '4': {'activeSceneId': 0,
                 'address': '9f42dfba2ab5',
                 'condition': 0,
                 'controls': [[{'name': 'dimmer0',
                                'type': 'Dimmer',
                                'value': 0.7019607843137254},
                               {'level': 0.0,
                                'max': 4000,
                                'min': 2700,
                                'name': 'temperature',
                                'type': 'CCT',
                                'value': 2700.0}]],
                 'dimLevel': 0.7019607843137254,
                 'firmwareVersion': '26.35',
                 'fixtureId': 3104,
                 'groupId': 0,
                 'id': 4,
                 'name': 'Mito soffitto',
                 'on': False,
                 'online': False,
                 'position': 11,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'Luminaire'},
           '5': {'activeSceneId': 0,
                 'address': '9a2737d73e94',
                 'condition': 0,
                 'controls': [[{'name': 'dimmer0',
                                'type': 'Dimmer',
                                'value': 0.6823529411764706},
                               {'level': 0.0,
                                'max': 4000,
                                'min': 2700,
                                'name': 'temperature',
                                'type': 'CCT',
                                'value': 2700.0}]],
                 'dimLevel': 0.6823529411764706,
                 'firmwareVersion': '26.35',
                 'fixtureId': 3104,
                 'groupId': 0,
                 'id': 5,
                 'name': 'Mito soffitto',
                 'on': False,
                 'online': False,
                 'position': 12,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'Luminaire'},
           '6': {'activeSceneId': 0,
                 'address': '1c9fd0016eed',
                 'condition': 0,
                 'controls': [[{'name': 'dimmer0',
                                'type': 'Dimmer',
                                'value': 0.0},
                               {'name': 'vertical',
                                'type': 'Vertical',
                                'value': 0.0}]],
                 'dimLevel': 0.0,
                 'firmwareVersion': '26.24',
                 'fixtureId': 816,
                 'groupId': 0,
                 'id': 6,
                 'name': 'Sento',
                 'on': False,
                 'online': False,
                 'position': 13,
                 'priority': 0,
                 'status': 'ok',
                 'type': 'Luminaire'}}}
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=1 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=2 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=3 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=4 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=5 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=6 - online - Setting unit to offline
2022-12-05 19:26:06.521 DEBUG (MainThread) [aiocasambi.unit] unit_id=1001 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1002 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1003 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1004 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1005 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1008 - online - Setting unit to offline
2022-12-05 19:26:06.522 DEBUG (MainThread) [aiocasambi.unit] unit_id=1009 - online - Setting unit to offline
2022-12-05 19:26:06.523 DEBUG (MainThread) [aiocasambi.unit] unit_id=1010 - online - Setting unit to offline
2022-12-05 19:26:06.523 DEBUG (MainThread) [aiocasambi.unit] unit_id=1011 - online - Setting unit to offline
2022-12-05 19:26:06.523 DEBUG (MainThread) [aiocasambi.unit] unit_id=1012 - online - Setting unit to offline
2022-12-05 19:26:06.523 DEBUG (MainThread) [aiocasambi.unit] unit_id=1013 - online - Setting unit to offline
2022-12-05 19:26:06.523 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] signalling_callback called signal: unit pull update data: ['Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-be08f02ce486', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-eb3eb1c38a05', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-e2150000bc90', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9f42dfba2ab5', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9a2737d73e94', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-1c9fd0016eed', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-', 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-']
2022-12-05 19:26:06.523 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-be08f02ce486 lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-eb3eb1c38a05 lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-e2150000bc90 lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9f42dfba2ab5 lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9a2737d73e94 lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-1c9fd0016eed lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.524 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [custom_components.casambi.casambi.CasambiController] update_light_state: unit: Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR- lights: []
2022-12-05 19:26:06.525 DEBUG (MainThread) [aiocasambi.controller] initialize getting unit state for all units in network_ids: {'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR'}
2022-12-05 19:26:06.530 DEBUG (MainThread) [aiocasambi.controller] init_unit_state_controls unique_ids: ['Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-be08f02ce486',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-eb3eb1c38a05',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-e2150000bc90',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9f42dfba2ab5',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-9a2737d73e94',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-1c9fd0016eed',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-',
 'Ief5qF3PJlyo8bijdSXHSx0iVJjoGfXR-']
```

And when it comes to unit_id 7, the error occurs

```
2022-12-05 19:26:07.713 DEBUG (MainThread) [aiocasambi.unit] unit_id=6 - setter controls - Adding following control to controls: {'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}
2022-12-05 19:26:07.713 DEBUG (MainThread) [aiocasambi.unit] unit_id=6 - setter controls - Adding following control to controls: {'name': 'vertical', 'type': 'Vertical', 'value': 0.0}
2022-12-05 19:26:07.714 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Casambi for casambi
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 365, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/casambi/__init__.py", line 45, in async_setup_entry
    controller = hass.data[DOMAIN][CONF_CONTROLLER] = await async_create_controller(hass, config)
  File "/config/custom_components/casambi/utils.py", line 80, in async_create_controller
    await aiocasambi_controller.initialize()
  File "/usr/local/lib/python3.10/site-packages/aiocasambi/controller.py", line 840, in initialize
    await self.init_unit_state_controls(network_id=network_id)
  File "/usr/local/lib/python3.10/site-packages/aiocasambi/controller.py", line 571, in init_unit_state_controls
    network_id = match.group("network_id")
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by hellqvio86** [comment]
Ok, the problem is that the unique id has been changed to be _<network_id>-<mac address>_ , since thats an unique identifier, the old one _<network_id><unit id>_ isn't

**Comment by hellqvio86** [comment]
I just released a new version, that release should fallback on the old unique id if mac address is not set, please try out version **0.115**

**Comment by sMauldaeschle** [comment]
It looks like there's a different issue now:

```
2022-12-05 21:33:06.885 DEBUG (MainThread) [aiocasambi.controller] request: 404 text/html <ClientResponse(https://door.casambi.com/v1/fixtures/100002) [404 Not Found]>
<CIMultiDictProxy('Date': 'Mon, 05 Dec 2022 20:33:06 GMT', 'Access-Control-Allow-Origin': '*', 'Access-Control-Allow-Methods': 'POST,GET,OPTIONS,PUT,DELETE,HEAD', 'Access-Control-Allow-Headers': '*', 'Access-Control-Max-Age': '728000', 'Access-Control-Allow-Credentials': 'true', 'Content-Type': 'text/html; charset=ISO-8859-1', 'Cache-Control': 'must-revalidate,no-cache,no-store', 'Content-Length': '145')>

2022-12-05 21:33:06.886 ERROR (MainThread) [custom_components.casambi.utils] Unknown Casambi communication error occurred!
```

**Comment by hellqvio86** [comment]
Do you get an exception? Otherwise that error you have to live with, they don't support the fixture id, which means you will not get the brand and model of the light in home assistant

**Comment by hellqvio86** [comment]
Its casting an exception, you have a new version that will fail a bit more "gracefully", manufacturer and model will not work for you, they will be set to "Casambi". New version is **v0.116**-

**Comment by sMauldaeschle** [comment]
Unfortunately it still raises the exception. I did test 115 and 116. A fallback to the old style would be awesome since that worked very stable and at least in my case (and hope most of the cases) the unit_id was unique.

**Comment by hellqvio86** [comment]
Can you give some more debug log so I see the stack trace, catchning the wrong exception then and this is new functionality that is not working for you, code for getting the right model and brand (fixture information) when homeassistant starts up. So nothing with unit id.

**Comment by hellqvio86** [comment]
I have released a new version that handles the exception **v0.117**.

**Comment by sMauldaeschle** [comment]
Looks like that one is covered. The new warning shows up but no more error. Great!
The only thing is now, that the Hue devices are not usable any more. The entities all show up as unavailable. Additionally the devices where the fixture_id is found show as Casambi/Board. The ones that have no fixture_id do not show with a manufacturer oder model at all.
<img width="1093" alt="Screenshot 2022-12-06 215559" src="https://user-images.githubusercontent.com/45919533/206021140-83fca2c3-ceb0-4056-8281-b0eb3d451397.png">
<img width="1109" alt="Screenshot 2022-12-06 215650" src="https://user-images.githubusercontent.com/45919533/206021247-e9337c46-1416-4f2f-9d6f-9700aa09fb5a.png">

**Comment by hellqvio86** [comment]
Please make sure that aiocasambi is reporting that they are online, everything that is reported as offline (online=false) is disabled.

Models are fetched from the fixture api call direct during startup and home assistant is only calling the integration ones, so if the information is not set you will not get the right information and you get a 404 om the call ( https://door.casambi.com/v1/fixtures/100002)  so please report that to casambis support, they need to fix it on their side.

**Comment by sMauldaeschle** [comment]
I will report the missing/wrong fixture information to Casambi. The other issue was a funny thing. Maybe with some update (at least i didn't no of so far) there came a button in the app settings to enable Hue. That needed to be activated on the orbsmart device running the Occhio/Casambi app in gateway mode.

**Comment by hellqvio86** [comment]
Great that you found the issue, please report back if they don't want to address the 404. An workaround would be to just do a local lookup, the only thing that is used is oem/brand and the model. But its better if they fix it in the api 🙂
